### ISSUE TITLE
Mod incompatibility: New TARDIS Mod

### ISSUE THREAD

**Issue by Zolton21** [nonamecrackers2/crackers-wither-storm-mod#1150]
**Minecraft version**
1.16.5
**Mod version**
1.0.3
**Describe the bug**
Minecraft crashes after any mob enters inside the tardis
**To Reproduce**
1. Create mc world
2. Spawn Brocken Exterior
3. Give it Ender Pearls/Ender Eyes/Bells/Clocks/Compass until the door opens
4. Spawn any mob(for example, cow)
5. Push him through the door
6. See the crash

**Crash Reports / Logs**
---- Minecraft Crash Report ----
// My bad.

Time: 26.04.2023, 19:23
Description: Saving entity NBT

java.lang.NullPointerException: Cannot invoke "nonamecrackers2.witherstormmod.common.capability.EntityCapability.write()" because "instance" is null
	at nonamecrackers2.witherstormmod.common.capability.EntityCapability$Storage.writeNBT(EntityCapability.java:38) ~[witherstormmod:1.16.5-1.0.3] {re:classloading}
	at nonamecrackers2.witherstormmod.common.capability.EntityCapability$Storage.writeNBT(EntityCapability.java:33) ~[witherstormmod:1.16.5-1.0.3] {re:classloading}
	at net.minecraftforge.common.capabilities.Capability.writeNBT(Capability.java:100) ~[forge:?] {re:classloading,re:mixin}
	at nonamecrackers2.witherstormmod.common.capability.EntityCapability$Serializable.serializeNBT(EntityCapability.java:68) ~[witherstormmod:1.16.5-1.0.3] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:113) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.serializeCaps(CapabilityProvider.java:122) ~[forge:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1407) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.entity.Entity.func_180432_n(Entity.java:2110) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at net.tardis.mod.helper.TeleportUtil.teleportEntityInterdimensional(TeleportUtil.java:121) ~[tardis:1.5.4] {re:classloading}
	at net.tardis.mod.helper.TeleportUtil.handleEntityTeleport(TeleportUtil.java:95) ~[tardis:1.5.4] {re:classloading}
	at net.tardis.mod.helper.TeleportUtil.teleportEntity(TeleportUtil.java:40) ~[tardis:1.5.4] {re:classloading}
	at net.tardis.mod.helper.WorldHelper.teleportEntities(WorldHelper.java:587) ~[tardis:1.5.4] {re:mixin,re:classloading}
	at net.tardis.mod.tileentities.exteriors.ExteriorTile.transferEntities(ExteriorTile.java:533) ~[tardis:1.5.4] {re:classloading}
	at net.tardis.mod.tileentities.exteriors.ExteriorTile.func_73660_a(ExteriorTile.java:260) ~[tardis:1.5.4] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:372) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:tardis.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at nonamecrackers2.witherstormmod.common.capability.EntityCapability$Storage.writeNBT(EntityCapability.java:38) ~[witherstormmod:1.16.5-1.0.3] {re:classloading}
	at nonamecrackers2.witherstormmod.common.capability.EntityCapability$Storage.writeNBT(EntityCapability.java:33) ~[witherstormmod:1.16.5-1.0.3] {re:classloading}
	at net.minecraftforge.common.capabilities.Capability.writeNBT(Capability.java:100) ~[forge:?] {re:classloading,re:mixin}
	at nonamecrackers2.witherstormmod.common.capability.EntityCapability$Serializable.serializeNBT(EntityCapability.java:68) ~[witherstormmod:1.16.5-1.0.3] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:113) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.serializeCaps(CapabilityProvider.java:122) ~[forge:?] {re:computing_frames,re:mixin,re:classloading}
-- Entity being saved --
Details:
	Entity Type: minecraft:zombie (net.minecraft.entity.monster.ZombieEntity)
	Entity ID: 42791
	Entity Name: Zombie
	Entity's Exact location: 742.61, 76.86, 178.70
	Entity's Block location: World: (742,76,178), Chunk: (at 6,4,2 in 46,11; contains blocks 736,0,176 to 751,255,191), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.01, -0.14, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.entity.Entity.toString()" because the return value of "net.minecraft.entity.Entity.func_184187_bx()" is null
Stacktrace:
	at net.minecraft.entity.Entity.func_189511_e(Entity.java:1407) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at net.minecraft.entity.Entity.func_180432_n(Entity.java:2110) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tardis.mixins.json:EntityMixin,pl:mixin:APP:create.mixins.json:EntityContraptionInteractionMixin,pl:mixin:A}
	at net.tardis.mod.helper.TeleportUtil.teleportEntityInterdimensional(TeleportUtil.java:121) ~[tardis:1.5.4] {re:classloading}
	at net.tardis.mod.helper.TeleportUtil.handleEntityTeleport(TeleportUtil.java:95) ~[tardis:1.5.4] {re:classloading}
	at net.tardis.mod.helper.TeleportUtil.teleportEntity(TeleportUtil.java:40) ~[tardis:1.5.4] {re:classloading}
	at net.tardis.mod.helper.WorldHelper.teleportEntities(WorldHelper.java:587) ~[tardis:1.5.4] {re:mixin,re:classloading}
	at net.tardis.mod.tileentities.exteriors.ExteriorTile.transferEntities(ExteriorTile.java:533) ~[tardis:1.5.4] {re:classloading}
	at net.tardis.mod.tileentities.exteriors.ExteriorTile.func_73660_a(ExteriorTile.java:260) ~[tardis:1.5.4] {re:classloading}

-- Block entity being ticked --
Details:
	Name: weeping_angels:2005_exterior // craig.software.mc.angels.compat.tardis.AbPropTile
	Block: Block{weeping_angels:2005_exterior}[facing=north,waterlogged=false]
	Block location: World: (742,77,179), Chunk: (at 6,4,3 in 46,11; contains blocks 736,0,176 to 751,255,191), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Block: Block{weeping_angels:2005_exterior}[facing=north,waterlogged=false]
	Block location: World: (742,77,179), Chunk: (at 6,4,3 in 46,11; contains blocks 736,0,176 to 751,255,191), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:TileWorldHookMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:372) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:tardis.mixins.json:ServerWorldMixin,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Zolton21'/349, l='ServerLevel[Новий світ]', x=742.37, y=76.00, z=175.94]]
	Chunk stats: ServerChunkCache: 4210
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,80,80), Chunk: (at 0,5,0 in -8,5; contains blocks -128,0,80 to -113,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 679408 game time, 7866 day time
	Level name: Новий світ
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 48279 (now: false), thunder time: 87961 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 7793016832 bytes (7432 MB) / 13314818048 bytes (12698 MB) up to 16106127360 bytes (15360 MB)
	CPUs: 12
	JVM Flags: 13 total; -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:-ZUncommit -XX:ZCollectionInterval=5 -XX:ZAllocationSpikeTolerance=2.0 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -Xms2048M -Xmx15360M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		supermartijn642configlib-1.1.6-forge-mc1.16.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6               |DONE      |Manifest: NOSIGNATURE
		cgm-1.2.6-1.16.5.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.2.6               |DONE      |Manifest: NOSIGNATURE
		weeping_angels-36.0.1.jar                         |Weeping Angels                |weeping_angels                |36.0.1              |DONE      |Manifest: NOSIGNATURE
		Far_From_Home-1.16.5-7.6.jar                      |Far From Home 7 Premium       |ffh7p                         |0.0                 |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.153.jar                          |Just Enough Items             |jei                           |7.7.1.153           |DONE      |Manifest: NOSIGNATURE
		connectivity-2.3-1.16.5.jar                       |Connectivity Mod              |connectivity                  |2.3-1.16.5          |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.1.2.457.jar                    |Mekanism                      |mekanism                      |10.1.2              |DONE      |Manifest: NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5p6.jar                     |Journeymap                    |journeymap                    |5.8.5p6             |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		OpenTerrainGenerator-1.16.5-0.1.10.jar            |Open Terrain Generator        |otg                           |1.16.5-0.1.10       |DONE      |Manifest: NOSIGNATURE
		u_team_core-1.16.5-3.2.1.229.jar                  |U Team Core                   |uteamcore                     |3.2.1.229           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		mcjtylib-1.16-5.1.8.jar                           |McJtyLib                      |mcjtylib                      |1.16-5.1.8          |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.16-2.1.5.jar                        |RFToolsBase                   |rftoolsbase                   |1.16-2.1.5          |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.11-1.16.5.jar                      |Ice and Fire                  |iceandfire                    |2.1.11-1.16.5       |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.1.2.457.jar          |Mekanism: Generators          |mekanismgenerators            |10.1.2              |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.16.5-0.12.1.133.jar         |Just Enough Resources         |jeresources                   |0.12.1.133          |DONE      |Manifest: NOSIGNATURE
		Tardis-Mod-1.16.5-1.5.4.jar                       |Tardis Mod                    |tardis                        |1.5.4               |DONE      |Manifest: NOSIGNATURE
		vortexmanipulators-1.4C.jar                       |More Vortex Manipulators      |vortexmanipulators            |1.4B                |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.18.4b.jar                |Supplementaries               |supplementaries               |0.18.2              |DONE      |Manifest: NOSIGNATURE
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		ironchest-1.16.5-11.2.21.jar                      |Iron Chests                   |ironchest                     |1.16.5-11.2.21      |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		useful_backpacks-1.16.5-1.12.1.103.jar            |Useful Backpacks              |usefulbackpacks               |1.12.1.103          |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		morevillagers-FORGE-1.16.5-1.5.5.jar              |More Villagers                |morevillagers                 |1.5.5               |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.16-3.1.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.7          |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-8.4.7.jar                     |Applied Energistics 2         |appliedenergistics2           |8.4.7               |DONE      |Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		[1.16]+Regeneration-36.0.4.jar                    |Regeneration                  |regen                         |36.0.4              |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.16.5-10.1.2.457.jar           |Mekanism: Additions           |mekanismadditions             |10.1.2              |DONE      |Manifest: NOSIGNATURE
		endrem-5.0.3-R-1.16.5.jar                         |End Remastered                |endrem                        |5.0.3-R-1.16.5      |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.16.5.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |DONE      |Manifest: NOSIGNATURE
		dalekmod-67.0.0.jar                               |Dalek Mod                     |dalekmod                      |67.0.0              |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.2.jar                             |betterfpsdist mod             |betterfpsdist                 |1.2                 |DONE      |Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |DONE      |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.8.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.8.2      |DONE      |Manifest: NOSIGNATURE
		eidolon-0.2.7.jar                                 |Eidolon                       |eidolon                       |0.2.7               |DONE      |Manifest: NOSIGNATURE
		temporal_additions-1.16.5-0.2.1.jar               |Temporal Additions            |tadditions                    |0.2.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		cofh_core-1.16.5-1.5.2.22.jar                     |CoFH Core                     |cofh_core                     |1.5.2.22            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.7.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.7        |DONE      |Manifest: NOSIGNATURE
		artrongen-1.1.jar                                 |Artron Converters             |artrongen                     |1.1                 |DONE      |Manifest: NOSIGNATURE
		JustEnoughProfessions-1.16.5-1.2.2.jar            |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.5.2.jar                   |Storage Drawers               |storagedrawers                |8.5.2               |DONE      |Manifest: NOSIGNATURE
		FluxNetworks-1.16.5-6.2.1.14.jar                  |Flux Networks                 |fluxnetworks                  |6.2.1.14            |DONE      |Manifest: NOSIGNATURE
		witherstormmod-1.16.5-1.0.3.jar                   |Cracker's Wither Storm Mod    |witherstormmod                |1.0.3               |DONE      |Manifest: NOSIGNATURE
		obfuscate-0.6.3-1.16.5.jar                        |Obfuscate                     |obfuscate                     |0.6.3               |DONE      |Manifest: NOSIGNATURE
		notenoughtardis-2.0+-+1.16+Update.jar             |Not Enough TARDIS             |notenoughtardis               |2.0 - 1.16 Update   |DONE      |Manifest: NOSIGNATURE
		TM-SpaceExtended.jar                              |Extended Space                |tmspaceexpand                 |1.0                 |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.1.2.457.jar               |Mekanism: Tools               |mekanismtools                 |10.1.2              |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.4.0.jar                |AppleSkin                     |appleskin                     |2.4.0+mc1.16.4      |DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.2.2-forge-mc1.16.jar               |Chunk Loaders                 |chunkloaders                  |1.2.2               |DONE      |Manifest: NOSIGNATURE
		Biomes-You-Go-1.3.6-MCV-1.16.5.jar                |Oh The Biomes You'll Go       |byg                           |1.3.4               |DONE      |Manifest: NOSIGNATURE
		Quick+Harvest-1.16.5-1.5.1.jar                    |Quick Harvest                 |quickharvest                  |1.5.1               |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.16.5-2.11.6.jar                     |FallingTree                   |fallingtree                   |2.11.5              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		CosmeticArmorReworked-1.16.5-v5.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v5           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		CodeChickenLib-1.16.5-4.0.7.445-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.7.445           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.16.5-2.8.0.170-universal.jar       |EnderStorage                  |enderstorage                  |2.8.0.170           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		BrandonsCore-1.16.5-3.0.15.248-universal.jar      |Brandon's Core                |brandonscore                  |3.0.15.248          |DONE      |Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		Draconic-Evolution-1.16.5-3.0.28.500-universal.jar|Draconic Evolution            |draconicevolution             |3.0.28.500          |DONE      |Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.16.5-1.25.9.jar                     |Ars Nouveau                   |ars_nouveau                   |1.25.9              |DONE      |Manifest: NOSIGNATURE
		createaddition-1.16.5-20220129a.jar               |Create Crafts & Additions     |createaddition                |1.16.5-20220129a    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b12dd1fa-cdf0-49ef-a890-73706b44316f
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['Zolton21'/349, l='ServerLevel[Новий світ]', x=742.37, y=76.00, z=175.94]]
	Data Packs: vanilla, mod:supermartijn642configlib, mod:cgm, mod:weeping_angels (incompatible), mod:ffh7p, mod:jei, mod:invtweaks (incompatible), mod:journeymap (incompatible), mod:citadel (incompatible), mod:otg, mod:uteamcore, mod:mcjtylib, mod:rftoolsbase, mod:iceandfire, mod:jeresources, mod:tardis, mod:vortexmanipulators, mod:supplementaries, mod:selene, mod:ironchest, mod:usefulbackpacks, mod:morevillagers, mod:theoneprobe, mod:appliedenergistics2 (incompatible), mod:regen, mod:endrem (incompatible), mod:supermartijn642corelib, mod:dalekmod, mod:flywheel, mod:create, mod:curios, mod:eidolon, mod:tadditions, mod:forge, mod:cofh_core, mod:patchouli (incompatible), mod:gravestone, mod:artrongen, mod:justenoughprofessions, mod:storagedrawers (incompatible), mod:fluxnetworks, mod:obfuscate, mod:notenoughtardis, mod:tmspaceexpand, mod:appleskin, mod:chunkloaders, mod:byg, mod:quickharvest, mod:fallingtree, mod:cosmeticarmorreworked (incompatible), mod:codechickenlib (incompatible), mod:enderstorage (incompatible), mod:brandonscore (incompatible), mod:draconicevolution (incompatible), mod:geckolib3 (incompatible), mod:ars_nouveau, mod:createaddition, file/BasicInteriorDatapack-1-16-v3.1.zip, file/Jade_ARS_Translation.zip, file/Jade_Corridor_Pack.zip, file/MidFords_Stattenheim.zip, file/Motobugs_1.16_Canon_Interior_Pack_V2.1.zip, file/Nautilus Resource Pack.zip, file/Squantoscouts_Nautilus_Corridors.zip, file/Type40Pack, file/dwdim, mod:connectivity, mod:mekanism, mod:mekanismgenerators, mod:mekanismadditions, mod:mekanismtools, mod:betterfpsdist, mod:witherstormmod
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Is OptiFine installed?**
no

**Comment by GrandmaPork** [comment]
Does this happen without CWSM?

**Comment by Zolton21** [comment]
No

**Comment by Zolton21** [comment]
> Does this happen without CWSM?

No

**Comment by nonamecrackers2** [comment]
Appears to be a Tardis problem, you could try reporting to them to see what they can do. Also, 1.16.5 is no longer supported, and considering that this is a compatibility issue this issue will be closed.
