### ISSUE TITLE
Morph not working

### ISSUE THREAD

**Issue by TheNotZen364** [nonamecrackers2/crackers-wither-storm-mod#20]
So when using the morph mod i morph into the storm and the game crashes

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 21/05/22 12:59
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at nonamecrackers2.witherstormmod.common.util.SegmentsManager.findSegments(SegmentsManager.java:160) ~[?:1.16.5-1.0.2] {re:classloading}
	at nonamecrackers2.witherstormmod.common.entity.WitherStormEntity.lambda$findSegments$40(WitherStormEntity.java:2995) ~[?:1.16.5-1.0.2] {re:classloading,pl:runtimedistcleaner:A}
	at nonamecrackers2.witherstormmod.common.entity.WitherStormEntity$$Lambda$6800/1347091043.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
	at nonamecrackers2.witherstormmod.common.entity.WitherStormEntity.findSegments(WitherStormEntity.java:2992) ~[?:1.16.5-1.0.2] {re:classloading,pl:runtimedistcleaner:A}
	at nonamecrackers2.witherstormmod.common.entity.WitherStormEntity.func_70071_h_(WitherStormEntity.java:1790) ~[?:1.16.5-1.0.2] {re:classloading,pl:runtimedistcleaner:A}
	at me.ichun.mods.morph.api.morph.MorphState.tick(MorphState.java:68) ~[?:10.1.1] {re:classloading}
	at me.ichun.mods.morph.common.morph.MorphInfoImpl.tick(MorphInfoImpl.java:81) ~[?:10.1.1] {re:classloading}
	at me.ichun.mods.morph.common.core.EventHandlerServer.onPlayerTick(EventHandlerServer.java:90) ~[?:10.1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_9_EventHandlerServer_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3254/643640236.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPostTick(BasicEventHooks.java:90) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:266) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:MixinPlayerEntity,pl:mixin:APP:morph.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5741/2047734670.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at nonamecrackers2.witherstormmod.common.util.SegmentsManager.findSegments(SegmentsManager.java:160) ~[?:1.16.5-1.0.2] {re:classloading}
	at nonamecrackers2.witherstormmod.common.entity.WitherStormEntity.lambda$findSegments$40(WitherStormEntity.java:2995) ~[?:1.16.5-1.0.2] {re:classloading,pl:runtimedistcleaner:A}
	at nonamecrackers2.witherstormmod.common.entity.WitherStormEntity$$Lambda$6800/1347091043.accept(Unknown Source) ~[?:?] {}
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51] {}
	at nonamecrackers2.witherstormmod.common.entity.WitherStormEntity.findSegments(WitherStormEntity.java:2992) ~[?:1.16.5-1.0.2] {re:classloading,pl:runtimedistcleaner:A}
	at nonamecrackers2.witherstormmod.common.entity.WitherStormEntity.func_70071_h_(WitherStormEntity.java:1790) ~[?:1.16.5-1.0.2] {re:classloading,pl:runtimedistcleaner:A}
	at me.ichun.mods.morph.api.morph.MorphState.tick(MorphState.java:68) ~[?:10.1.1] {re:classloading}
	at me.ichun.mods.morph.common.morph.MorphInfoImpl.tick(MorphInfoImpl.java:81) ~[?:10.1.1] {re:classloading}
	at me.ichun.mods.morph.common.core.EventHandlerServer.onPlayerTick(EventHandlerServer.java:90) ~[?:10.1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_9_EventHandlerServer_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3254/643640236.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPostTick(BasicEventHooks.java:90) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:266) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:MixinPlayerEntity,pl:mixin:APP:morph.mixins.json:PlayerEntityMixin,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.entity.player.ServerPlayerEntity)
	Entity ID: 1
	Entity Name: MSV4
	Entity's Exact location: -208.76, 25.28, 175.47
	Entity's Block location: World: (-209,25,175), Chunk: (at 15,1,15 in -14,10; contains blocks -224,0,160 to -209,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:classloading,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5741/2047734670.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1613250592 bytes (1538 MB) / 3288334336 bytes (3136 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.5.2.jar                       |iChunUtil                     |ichunutil                     |10.5.2              |DONE      |Manifest: NOSIGNATURE
		witherstormmod-1.16.5-1.0.2.jar                   |Cracker's Wither Storm Mod    |witherstormmod                |1.0.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Morph-1.16.5-10.1.1.jar                           |Morph                         |morph                         |10.1.1              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 5e90212a-9b82-4586-aee1-244f41585895
	Player Count: 1 / 8; [ServerPlayerEntity['MSV4'/1, l='ServerLevel[New World]', x=-208.76, y=25.28, z=175.47]]
	Data Packs: vanilla, mod:ichunutil, mod:witherstormmod, mod:forge, mod:morph
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 472.80
	OpenGlRenderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by nonamecrackers2** [comment]
Will be fixed in the next update
