### ISSUE TITLE
[Bug]: MCSM wither storm music and symbiont music not working though option is on

### ISSUE THREAD

**Issue by BTouu** [nonamecrackers2/crackers-wither-storm-mod#2090]
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

1.20.1-forge-47.2.1

### Describe the bug

spawn WS and the music did not play I refresh Sounds and nothing 

### Steps to Reproduce

spawn WS or symbiont

### Crash Reports/Logs

---- Minecraft Crash Report ---- // Don't do that.  Time: 2024-07-29 20:15:35 Description: Manually triggered debug crash  java.lang.Throwable: Manually triggered debug crash 	at net.minecraft.client.KeyboardHandler.m_90931_(KeyboardHandler.java:502) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1872) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.1.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.minecraft.client.KeyboardHandler.m_90931_(KeyboardHandler.java:502) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A} -- Manual crash details -- Details: 	Modules:  		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		AUDIOSES.DLL:Audio Session:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation 		CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTBASE.DLL:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.3672:Microsoft Corporation 		DBGHELP.DLL:Windows Image Helper:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation 		DEVOBJ.dll:Device Information Set DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		GDI32.dll:GDI Client DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		GLU32.dll:OpenGL Utility Library DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation 		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation 		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation 		MMDevApi.dll:MMDevice API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		MSCTF.dll:MSCTF Server DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		MpOav.dll:IOfficeAntiVirus Module:4.18.24060.7 (47d4bdd9064bc68e82ed85dd3a432e84e907a9be):Microsoft Corporation 		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		OpenAL.dll:Main implementation library:1.21.1: 		POWRPROF.dll:Power Profile Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation 		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		SETUPAPI.dll:Windows Setup API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		SHELL32.dll:Windows Shell Common Dll:10.0.22621.3810 (WinBuild.160101.0800):Microsoft Corporation 		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		WINSTA.dll:Winstation Library:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.3810 (WinBuild.160101.0800):Microsoft Corporation 		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		amsi.dll:Anti-Malware Scan Interface:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation 		apphelp.dll:Application Compatibility Client Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		awt.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		cfgmgr32.dll:Configuration Manager DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation 		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		cryptnet.dll:Crypto Network Related API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc.DLL:DHCP Client Service:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		dinput8.dll:Microsoft DirectInput:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		drvstore.dll:Driver Store API:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		dwmapi.dll:Microsoft Desktop Window Manager API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		dxcore.dll:DXCore:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		fastprox.dll:WMI Custom Marshaller:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		gdi32full.dll:GDI Client DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW 		icm32.dll:Microsoft Color Management Module (CMM):10.0.22621.3880 (WinBuild.160101.0800):Microsoft Corporation 		inputhost.dll:InputHost:10.0.22621.3810 (WinBuild.160101.0800):Microsoft Corporation 		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft 		jemalloc.dll 		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jna585633461638450574.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA) 		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft 		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation 		lwjgl.dll 		lwjgl_opengl.dll 		lwjgl_stb.dll 		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		msasn1.dll:ASN.1 Runtime APIs:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		mscms.dll:Microsoft Color Matching System DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation 		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		ntdll.dll:NT Layer DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation 		ntmarta.dll:Windows NT MARTA provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:31.0.15.1694:NVIDIA Corporation 		nvspcap64.dll:NVIDIA Game Proxy:3.25.1.27:NVIDIA Corporation 		ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		opengl32.dll:OpenGL Client DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		profapi.dll:User Profile Basic API:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation 		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		resourcepolicyclient.dll:Resource Policy Client:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation 		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		sapi.dll:Speech API:5.3.26906.00 (WinBuild.160101.0800):Microsoft Corporation 		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22621.3810 (WinBuild.160101.0800):Microsoft Corporation 		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation 		uxtheme.dll:Microsoft UxTheme Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation 		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft 		wbemcomn.dll:WMI:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		wbemprox.dll:WMI:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		wbemsvc.dll:WMI:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation 		win32u.dll:Win32u:10.0.22621.3880 (WinBuild.160101.0800):Microsoft Corporation 		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation 		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		wldp.dll:Windows Lockdown Policy:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation 		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation 		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		xinput1_4.dll:Microsoft Common Controller API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation 		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft Stacktrace: 	at net.minecraft.client.KeyboardHandler.m_90931_(KeyboardHandler.java:502) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1872) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.1.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   -- Affected level -- Details: 	All players: 1 total; [LocalPlayer['The_Hero2244'/169, l='ClientLevel', x=1.39, y=135.95, z=-10.08]] 	Chunk stats: 961, 609 	Level dimension: minecraft:overworld 	Level spawn location: World: (0,117,0), Section: (at 0,5,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) 	Level time: 3054 game time, 3054 day time 	Server brand: forge 	Server type: Integrated singleplayer server Stacktrace: 	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:witherstormmod.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:735) ~[client-1.20.1-20230612.114412-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:witherstormmod.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.1.jar:?] {re:classloading,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.1.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: Yes 	Packs: vanilla, mod_resources  -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 11 (amd64) version 10.0 	Java Version: 17.0.8, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 1595475584 bytes (1521 MiB) / 2952790016 bytes (2816 MiB) up to 5368709120 bytes (5120 MiB) 	CPUs: 20 	Processor Vendor: GenuineIntel 	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700F 	Identifier: Intel64 Family 6 Model 151 Stepping 2 	Microarchitecture: Alder Lake 	Frequency (GHz): 2.11 	Number of physical packages: 1 	Number of physical CPUs: 12 	Number of logical CPUs: 20 	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x2489 	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 2.40 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 16384.00 	Memory slot #1 clockSpeed (GHz): 2.40 	Memory slot #1 type: DDR4 	Memory slot #2 capacity (MB): 8192.00 	Memory slot #2 clockSpeed (GHz): 2.40 	Memory slot #2 type: DDR4 	Memory slot #3 capacity (MB): 16384.00 	Memory slot #3 clockSpeed (GHz): 2.40 	Memory slot #3 type: DDR4 	Virtual memory max (MB): 196421.38 	Virtual memory used (MB): 12230.03 	Swap memory total (MB): 147456.00 	Swap memory used (MB): 0.00 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Launched Version: 1.20.1-forge-47.2.1 	Backend library: LWJGL version 3.3.1 build 7 	Backend API: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.94, NVIDIA Corporation 	Window size: 854x480 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge' 	Type: Integrated Server (map_client.txt) 	Graphics mode: fancy 	Resource Packs:  	Current Language: en_us 	CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700F 	Server Running: true 	Player Count: 1 / 8; [ServerPlayer['The_Hero2244'/169, l='ServerLevel[ejnwb]', x=1.39, y=135.95, z=-10.08]] 	Data Packs: vanilla, mod:crackerslib (incompatible), mod:witherstormmod, mod:forge 	Enabled Feature Flags: minecraft:vanilla 	World Generation: Experimental 	ModLauncher: 10.0.9+10.0.9+main.dcd20f30 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.5.jar eventbus PLUGINSERVICE  		fmlloader-1.20.1-47.2.1.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.20.1-47.2.1.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.20.1-47.2.1.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.20.1-47.2.1.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.20.1-47.2.1.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		crackerslib-forge-1.20.1-0.3.2.1.jar              |CrackersLib                   |crackerslib                   |1.20.1-0.3.2.1      |DONE      |Manifest: NOSIGNATURE 		witherstormmod-1.20.1-4.1-all.jar                 |Cracker's Wither Storm Mod    |witherstormmod                |4.1                 |DONE      |Manifest: NOSIGNATURE 		forge-1.20.1-47.2.1-universal.jar                 |Forge                         |forge                         |47.2.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90 	Crash Report UUID: 0b77d8ae-5feb-4cd7-b950-dc8bf515ddf2 	FML: 47.2 	Forge: net.minecraftforge:47.2.1

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Screenshot 2024-07-29 201402](https://github.com/user-attachments/assets/bf3d1fa7-82ba-4f5e-8da5-adef2f2b7bb6)

### Mod List

NONE

**Comment by nonamecrackers2** [comment]
Is the music slider up?
