### ISSUE TITLE
Wither Storm crashes game when in health bar range

### ISSUE THREAD

**Issue by hmelioo** [nonamecrackers2/crackers-wither-storm-mod#22]
An issue me and a few friends have been having is that whenever we approach the storm or it approaches us at a distance where the health bar is visible, the game lags out and eventually crashes.
Exit codes are usually a variant of the following:
The game crashed whilst tesselating block model with rgba
Error: java.lang.ArrayIndexOutOfBoundsException: 4
Exit Code: -1

This usually happens only with the earlier evolutions of the storm, though it has happened a few times with larger ones.

Full crash report:
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/21/22 2:23 PM
Description: Tesselating block model with rgba

java.lang.ArrayIndexOutOfBoundsException: 4
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.putBulkDataWithAlpha(BlockRenderingUtil.java:154) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.putQuadData(BlockRenderingUtil.java:124) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelFaceFlat(BlockRenderingUtil.java:101) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelFlat(BlockRenderingUtil.java:79) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelNoOcclusion(BlockRenderingUtil.java:47) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.renderer.entity.BlockClusterRenderer.render(BlockClusterRenderer.java:84) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.renderer.entity.BlockClusterRenderer.func_225623_a_(BlockClusterRenderer.java:40) ~[?:1.16.5-1.0.1] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:2120) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.setSectionDirty}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1742) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.setSectionDirty}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:witherstormmod.mixins.json:IMixinGameRenderer,pl:mixin:APP:witherstormmod.mixins.json:MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:witherstormmod.mixins.json:IMixinGameRenderer,pl:mixin:APP:witherstormmod.mixins.json:MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$465/1812200214.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.putBulkDataWithAlpha(BlockRenderingUtil.java:154) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.putQuadData(BlockRenderingUtil.java:124) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelFaceFlat(BlockRenderingUtil.java:101) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelFlat(BlockRenderingUtil.java:79) ~[?:1.16.5-1.0.1] {re:classloading}
-- Block model being tesselated --
Details:
	Block: Block{minecraft:tall_grass}[half=upper]
	Block location: World: (-146,74,61), Chunk: (at 14,4,13 in -10,3; contains blocks -160,0,48 to -145,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelNoOcclusion(BlockRenderingUtil.java:47) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.renderer.entity.BlockClusterRenderer.render(BlockClusterRenderer.java:84) ~[?:1.16.5-1.0.1] {re:classloading}
	at nonamecrackers2.witherstormmod.client.renderer.entity.BlockClusterRenderer.func_225623_a_(BlockClusterRenderer.java:40) ~[?:1.16.5-1.0.1] {re:classloading}

-- Entity being rendered --
Details:
	Entity Type: witherstormmod:block_cluster (nonamecrackers2.witherstormmod.common.entity.BlockClusterEntity)
	Entity ID: 193
	Entity Name: Block Cluster
	Entity's Exact location: -145.15, 74.00, 61.82
	Entity's Block location: World: (-146,74,61), Chunk: (at 14,4,13 in -10,3; contains blocks -160,0,48 to -145,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.19, 0.39, -0.24
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: nonamecrackers2.witherstormmod.client.renderer.entity.BlockClusterRenderer@2dda66b8
	Location: 43.91,3.32,-28.40 - World: (43,3,-29), Chunk: (at 11,0,3 in 2,-2; contains blocks 32,0,-32 to 47,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 6.3187494
	Delta: 0.9200028
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:2120) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.setSectionDirty}
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1742) ~[?:?] {re:classloading,xf:OptiFine:default,xf:fml:journeymap:WorldRenderer.setSectionDirty}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1022) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:witherstormmod.mixins.json:IMixinGameRenderer,pl:mixin:APP:witherstormmod.mixins.json:MixinGameRenderer,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['ConcertBflat'/195, l='ClientLevel', x=-189.08, y=69.03, z=90.23]]
	Chunk stats: Client Chunk Cache: 841, 596
	Level dimension: minecraft:overworld
	Level spawn location: World: (-192,63,144), Chunk: (at 0,3,0 in -12,9; contains blocks -192,0,144 to -177,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4788 game time, 4788 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$465/1812200214.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2207459928 bytes (2105 MB) / 3992977408 bytes (3808 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		witherstormmod-1.16.5-1.0.1.jar                   |Cracker's Wither Storm Mod    |witherstormmod                |1.0.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		mostructures-forge-1.2.0-1.16.5.jar               |Mo' Structures                |mostructures                  |1.2.0-1.16.5        |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.486-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.486   |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.1.2.457.jar               |Mekanism: Tools               |mekanismtools                 |10.1.2              |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.16.5-10.1.2.457.jar           |Mekanism: Additions           |mekanismadditions             |10.1.2              |DONE      |Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.7.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.7        |DONE      |Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.3.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.5.jar                       |Journeymap                    |journeymap                    |5.8.5               |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.1.2.457.jar          |Mekanism: Generators          |mekanismgenerators            |10.1.2              |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.1.2.457.jar                    |Mekanism                      |mekanism                      |10.1.2              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: f23fa4bb-ed5c-43b2-b01d-dc64e39fb84a
	Launched Version: 1.16.5-forge-36.2.34
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 496.49, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: file/sus.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 496.49
	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by nonamecrackers2** [comment]
Are you using shaders?

**Comment by nonamecrackers2** [comment]
Nevermind, looks like you're using the internal ones. Try turning off "Block Cluster Colouring" in the client config

**Comment by hmelioo** [comment]
That seems to have worked, thank you!

**Comment by nonamecrackers2** [comment]
Np

**Comment by RedstoneGithub** [comment]
Can this fix be put in the mod description on CurseForge?
