### ISSUE TITLE
Game crash.

### ISSUE THREAD

**Issue by Niu-se** [nonamecrackers2/crackers-wither-storm-mod#467]
Minecraft version
1.16.5

Mod version
Wither Storm:1.0.2.4

Describe the bug
The game crashes when the boss is born.

Crash Reports / Logs
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/10/22 7:45 PM
Description: Tesselating block model with rgba

java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.putBulkDataWithAlpha(BlockRenderingUtil.java:154) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.putQuadData(BlockRenderingUtil.java:124) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelFaceFlat(BlockRenderingUtil.java:101) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelFlat(BlockRenderingUtil.java:79) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelNoOcclusion(BlockRenderingUtil.java:47) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.renderer.entity.BlockClusterRenderer.render(BlockClusterRenderer.java:86) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.renderer.entity.BlockClusterRenderer.func_225623_a_(BlockClusterRenderer.java:39) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:2120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:483) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4840) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:949) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:witherstormmod.mixins.json:IMixinGameRenderer,pl:mixin:APP:witherstormmod.mixins.json:MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:693) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:witherstormmod.mixins.json:IMixinGameRenderer,pl:mixin:APP:witherstormmod.mixins.json:MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.putBulkDataWithAlpha(BlockRenderingUtil.java:154) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.putQuadData(BlockRenderingUtil.java:124) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelFaceFlat(BlockRenderingUtil.java:101) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelFlat(BlockRenderingUtil.java:79) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
-- Block model being tesselated --
Details:
	Block: Block{minecraft:seagrass}
	Block location: World: (8,62,7), Chunk: (at 8,3,7 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at nonamecrackers2.witherstormmod.client.util.BlockRenderingUtil.renderModelNoOcclusion(BlockRenderingUtil.java:47) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.renderer.entity.BlockClusterRenderer.render(BlockClusterRenderer.java:86) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}
	at nonamecrackers2.witherstormmod.client.renderer.entity.BlockClusterRenderer.func_225623_a_(BlockClusterRenderer.java:39) ~[witherstormmod:1.16.5-1.0.2.4] {re:classloading}

-- Entity being rendered --
Details:
	Entity Type: witherstormmod:block_cluster (nonamecrackers2.witherstormmod.common.entity.BlockClusterEntity)
	Entity ID: 1515
	Entity Name: Block Cluster
	Entity's Exact location: 8.63, 62.02, 7.11
	Entity's Block location: World: (8,62,7), Chunk: (at 8,3,7 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.06, 0.51, -0.20
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: nonamecrackers2.witherstormmod.client.renderer.entity.BlockClusterRenderer@4b27821c
	Location: 8.75,-16.91,-3.90 - World: (8,-17,-4), Chunk: (at 8,-2,12 in 0,-1; contains blocks 0,0,-16 to 15,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Rotation: 1.3000001
	Delta: 0.30001807
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:311) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:2120) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:483) ~[?:?] {re:classloading}
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4840) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:949) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:witherstormmod.mixins.json:IMixinGameRenderer,pl:mixin:APP:witherstormmod.mixins.json:MixinGameRenderer,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['test'/267, l='ClientLevel', x=-0.17, y=76.96, z=11.14]]
	Chunk stats: Client Chunk Cache: 625, 558
	Level dimension: minecraft:overworld
	Level spawn location: World: (-144,64,256), Chunk: (at 0,4,0 in -9,16; contains blocks -144,0,256 to -129,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1829 game time, 1829 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.15, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7001018336 bytes (6676 MB) / 8438939648 bytes (8048 MB) up to 9714008064 bytes (9264 MB)
	CPUs: 12
	JVM Flags: 13 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx9255m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		witherstormmod-1.16.5-1.0.2.4.jar                 |Cracker's Wither Storm Mod    |witherstormmod                |1.0.2.4             |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Crash Report UUID: ac7844df-c36a-436c-b8a7-a5d1430be171
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.59, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, programer_art, mod_resources, file/UltimaCraft_Leaf_(v.1.0)_(1.16).zip, file/UltimaCraft_Flat_(b.1.0).zip, file/UltimaCraft_(v.1.1)_(1.16).zip, file/UltimaCraft_PBR_(v.1.1)_(1.16)_lab.zip, file/Unity-1.16.X-Dark-0.7.1.zip, file/FreshAnimations_v1.6.1.zip, file/visual-impairxfreshanimations-test1.1.zip
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders_v4.4.zip
	OpenGlVersion: 4.6.0 NVIDIA 516.59
	OpenGlRenderer: NVIDIA GeForce RTX 2070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by dgc0312** [comment]
delete your shaders. NOW

**Comment by Niu-se** [comment]
Thank you.Problem solved.

**Comment by nonamecrackers2** [comment]
Or disable block cluster coloring. You do not need to "delete" your shaders.

**Comment by dgc0312** [comment]
better get rid of them
