### ISSUE TITLE
Unable to create a new map and log into

### ISSUE THREAD

**Issue by Ritter0928** [nonamecrackers2/crackers-wither-storm-mod#888]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 29/01/23, 10:55 a. m.
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.18.2 of loader 'TRANSFORMER' @2149594a)
	at nonamecrackers2.witherstormmod.common.event.WitherSicknessEvents.onWorldTick(WitherSicknessEvents.java:36) ~[witherstormmod-1.18.2-2.1.1.jar%2353!/:1.18.2-2.1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_34_WitherSicknessEvents_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreWorldTick(ForgeEventFactory.java:895) ~[forge-1.18.2-40.2.1-universal.jar%2359!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1717) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1021) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.1.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at nonamecrackers2.witherstormmod.common.event.WitherSicknessEvents.onWorldTick(WitherSicknessEvents.java:36) ~[witherstormmod-1.18.2-2.1.1.jar%2353!/:1.18.2-2.1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_34_WitherSicknessEvents_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreWorldTick(ForgeEventFactory.java:895) ~[forge-1.18.2-40.2.1-universal.jar%2359!/:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Ritter0928'/73, l='ClientLevel', x=-9.50, y=63.00, z=8.50]]
	Chunk stats: 1849, 458
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,63,0), Section: (at 0,15,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 50 game time, 50 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:witherstormmod.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2264) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:687) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.1.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 713845360 bytes (680 MiB) / 1946157056 bytes (1856 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3,59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 3,00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384,00
	Memory slot #1 clockSpeed (GHz): 3,00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28108,57
	Virtual memory used (MB): 11846,70
	Swap memory total (MB): 3584,00
	Swap memory used (MB): 0,00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.2-forge-40.2.1
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: Español (Venezuela)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Ritter0928'/73, l='ServerLevel[WSW]', x=-9.50, y=63.00, z=8.50]]
	Data Packs: vanilla, mod:witherstormmod (incompatible), mod:forge
	World Generation: Experimental
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		witherstormmod-1.18.2-2.1.1.jar                   |Cracker's Wither Storm Mod    |witherstormmod                |2.1.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.1-universal.jar                 |Forge                         |forge                         |40.2.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Crash Report UUID: 9d4ee905-49d0-4b26-9510-dc2469777ab0
	FML: 40.2
	Forge: net.minecraftforge:40.2.1

**Comment by myron-obsolete-account** [comment]
you dont really have to throw in the entire log as description bruh

**Comment by myron-obsolete-account** [comment]
mod might be incompatible with specific versions of forge, see #885

**Comment by Globalfirestorm10** [comment]
> you dont really have to throw in the entire log as description bruh
> 
> 

Exactly, you could've just attached the issue, provided some screenshots, and given a basic rundown of the issue.

**Comment by Globalfirestorm10** [comment]
> ---- Minecraft Crash Report ----
> 
> // Shall we play a game?
> 
> 
> 
> Time: 29/01/23, 10:55 a. m.
> 
> Description: Unexpected error
> 
> 
> 
> java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientLevel cannot be cast to class net.minecraft.server.level.ServerLevel (net.minecraft.client.multiplayer.ClientLevel and net.minecraft.server.level.ServerLevel are in module minecraft@1.18.2 of loader 'TRANSFORMER' @2149594a)
> 
> 	at nonamecrackers2.witherstormmod.common.event.WitherSicknessEvents.onWorldTick(WitherSicknessEvents.java:36) ~[witherstormmod-1.18.2-2.1.1.jar%2353!/:1.18.2-2.1.1] {re:classloading}
> 
> 	at net.minecraftforge.eventbus.ASMEventHandler_34_WitherSicknessEvents_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
> 
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
> 
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
> 
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
> 
> 	at net.minecraftforge.event.ForgeEventFactory.onPreWorldTick(ForgeEventFactory.java:895) ~[forge-1.18.2-40.2.1-universal.jar%2359!/:?] {re:classloading}
> 
> 	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1717) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 
> 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1021) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 
> 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 
> 	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.1.jar%2317!/:?] {}
> 
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
> 
> 
> 
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> ---------------------------------------------------------------------------------------
> 
> 
> 
> -- Head --
> 
> Thread: Render thread
> 
> Stacktrace:
> 
> 	at nonamecrackers2.witherstormmod.common.event.WitherSicknessEvents.onWorldTick(WitherSicknessEvents.java:36) ~[witherstormmod-1.18.2-2.1.1.jar%2353!/:1.18.2-2.1.1] {re:classloading}
> 
> 	at net.minecraftforge.eventbus.ASMEventHandler_34_WitherSicknessEvents_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
> 
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
> 
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
> 
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
> 
> 	at net.minecraftforge.event.ForgeEventFactory.onPreWorldTick(ForgeEventFactory.java:895) ~[forge-1.18.2-40.2.1-universal.jar%2359!/:?] {re:classloading}
> 
> -- Affected level --
> 
> Details:
> 
> 	All players: 1 total; [LocalPlayer['Ritter0928'/73, l='ClientLevel', x=-9.50, y=63.00, z=8.50]]
> 
> 	Chunk stats: 1849, 458
> 
> 	Level dimension: minecraft:overworld
> 
> 	Level spawn location: World: (0,63,0), Section: (at 0,15,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
> 
> 	Level time: 50 game time, 50 day time
> 
> 	Server brand: forge
> 
> 	Server type: Integrated singleplayer server
> 
> Stacktrace:
> 
> 	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:witherstormmod.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
> 
> 	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2264) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 
> 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:687) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 
> 	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2354!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.1.jar%2317!/:?] {}
> 
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
> 
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
> 
> 
> 
> 
> 
> -- Last reload --
> 
> Details:
> 
> 	Reload number: 1
> 
> 	Reload reason: initial
> 
> 	Finished: Yes
> 
> 	Packs: Default, Mod Resources
> 
> 
> 
> -- System Details --
> 
> Details:
> 
> 	Minecraft Version: 1.18.2
> 
> 	Minecraft Version ID: 1.18.2
> 
> 	Operating System: Windows 10 (amd64) version 10.0
> 
> 	Java Version: 17.0.1, Microsoft
> 
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 
> 	Memory: 713845360 bytes (680 MiB) / 1946157056 bytes (1856 MiB) up to 2147483648 bytes (2048 MiB)
> 
> 	CPUs: 12
> 
> 	Processor Vendor: AuthenticAMD
> 
> 	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
> 
> 	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
> 
> 	Microarchitecture: Zen 2
> 
> 	Frequency (GHz): 3,59
> 
> 	Number of physical packages: 1
> 
> 	Number of physical CPUs: 6
> 
> 	Number of logical CPUs: 12
> 
> 	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
> 
> 	Graphics card #0 vendor: NVIDIA (0x10de)
> 
> 	Graphics card #0 VRAM (MB): 4095,00
> 
> 	Graphics card #0 deviceId: 0x21c4
> 
> 	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
> 
> 	Memory slot #0 capacity (MB): 8192,00
> 
> 	Memory slot #0 clockSpeed (GHz): 3,00
> 
> 	Memory slot #0 type: DDR4
> 
> 	Memory slot #1 capacity (MB): 16384,00
> 
> 	Memory slot #1 clockSpeed (GHz): 3,00
> 
> 	Memory slot #1 type: DDR4
> 
> 	Virtual memory max (MB): 28108,57
> 
> 	Virtual memory used (MB): 11846,70
> 
> 	Swap memory total (MB): 3584,00
> 
> 	Swap memory used (MB): 0,00
> 
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 
> 	Launched Version: 1.18.2-forge-40.2.1
> 
> 	Backend library: LWJGL version 3.2.2 SNAPSHOT
> 
> 	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
> 
> 	Window size: 1920x1080
> 
> 	GL Caps: Using framebuffer using OpenGL 3.2
> 
> 	GL debug messages: 
> 
> 	Using VBOs: Yes
> 
> 	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
> 
> 	Type: Integrated Server (map_client.txt)
> 
> 	Graphics mode: fancy
> 
> 	Resource Packs: 
> 
> 	Current Language: Español (Venezuela)
> 
> 	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
> 
> 	Server Running: true
> 
> 	Player Count: 1 / 8; [ServerPlayer['Ritter0928'/73, l='ServerLevel[WSW]', x=-9.50, y=63.00, z=8.50]]
> 
> 	Data Packs: vanilla, mod:witherstormmod (incompatible), mod:forge
> 
> 	World Generation: Experimental
> 
> 	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
> 
> 	ModLauncher launch target: forgeclient
> 
> 	ModLauncher naming: srg
> 
> 	ModLauncher services: 
> 
> 		 mixin PLUGINSERVICE 
> 
> 		 eventbus PLUGINSERVICE 
> 
> 		 slf4jfixer PLUGINSERVICE 
> 
> 		 object_holder_definalize PLUGINSERVICE 
> 
> 		 runtime_enum_extender PLUGINSERVICE 
> 
> 		 capability_token_subclass PLUGINSERVICE 
> 
> 		 accesstransformer PLUGINSERVICE 
> 
> 		 runtimedistcleaner PLUGINSERVICE 
> 
> 		 mixin TRANSFORMATIONSERVICE 
> 
> 		 fml TRANSFORMATIONSERVICE 
> 
> 	FML Language Providers: 
> 
> 		minecraft@1.0
> 
> 		lowcodefml@null
> 
> 		javafml@null
> 
> 	Mod List: 
> 
> 		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
> 
> 		witherstormmod-1.18.2-2.1.1.jar                   |Cracker's Wither Storm Mod    |witherstormmod                |2.1.1               |DONE      |Manifest: NOSIGNATURE
> 
> 		forge-1.18.2-40.2.1-universal.jar                 |Forge                         |forge                         |40.2.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
> 
> 	Crash Report UUID: 9d4ee905-49d0-4b26-9510-dc2469777ab0
> 
> 	FML: 40.2
> 
> 	Forge: net.minecraftforge:40.2.1

Use the recommended 1.19 build, the latest includes a breaking change

**Comment by nonamecrackers2** [comment]
#885
