### ISSUE TITLE
1.16.5 crash

### ISSUE THREAD

**Issue by miguelgamito** [nonamecrackers2/crackers-wither-storm-mod#918]
**1.16.5**
The version of Minecraft the mod is running on

**witherstormmod-1.16.5-1.0.2.4.jar)**
The version of the mod you are using

HI, i have been with this issue since i started a modded server with my friends and sometimes with no reason at all, it crash. This problem only happens when u try to enter into the server, sometimes i gotta reset or try a few times before i can join the game without the crash, and everything works perfectly until u disconnect or other player wants to join the world and have the same issue, so sometimes you can enter at the first attempt or u cant even after trying 6 times, however this is the log:

java.lang.IllegalStateException: Tag witherstormmod:wither_sickness_immune used before it was bound
    at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:131) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.tags.TagRegistry$NamedTag.func_230235_a_(TagRegistry.java:142) ~[?:?] {re:classloading,pl:accesstransformer:B}
    at net.minecraft.entity.EntityType.func_220341_a(EntityType.java:542) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
    at nonamecrackers2.witherstormmod.common.capability.WitherSicknessTracker.isActuallyImmune(WitherSicknessTracker.java:597) ~[?:1.16.5-1.0.2.4] {re:classloading}
    at nonamecrackers2.witherstormmod.common.capability.WitherSicknessTracker.tick(WitherSicknessTracker.java:186) ~[?:1.16.5-1.0.2.4] {re:classloading}
    at nonamecrackers2.witherstormmod.client.event.ClientWitherSicknessEvents.lambda$onClientTick$0(ClientWitherSicknessEvents.java:31) ~[?:1.16.5-1.0.2.4] {re:classloading}
    at nonamecrackers2.witherstormmod.client.event.ClientWitherSicknessEvents$$Lambda$36998/1295085643.accept(Unknown Source) ~[?:?] {}
    at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:151) ~[?:?] {re:mixin,re:classloading}
    at nonamecrackers2.witherstormmod.client.event.ClientWitherSicknessEvents.onClientTick(ClientWitherSicknessEvents.java:29) ~[?:1.16.5-1.0.2.4] {re:classloading}
    at net.minecraftforge.eventbus.ASMEventHandler_3127_ClientWitherSicknessEvents_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
    at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
    at net.minecraftforge.eventbus.EventBus$$Lambda$3172/812598172.invoke(Unknown Source) ~[?:?] {}
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
    at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:96) ~[?:?] {re:classloading}
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1544) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
    at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
    at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
    at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.39.jar:36.2] {}
    at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$512/471031651.call(Unknown Source) [forge-1.16.5-36.2.39.jar:36.2] {}
    at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
    at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
    at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
    at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}

im not the better on this things but i surely know that this is not a problem with an entity spawning on the chunk bcs even that other players can play while i cant, they go to my zone and dont get any problem. hopes this get fixed easy and fast, ty in advance

No Flywheel instalated

**Comment by nonamecrackers2** [comment]
Fixed in the latest 1.16.5 release
